iar_transforms:
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: inm-iar-analytics-playground
      dataset: dbt_rwyatt
      threads: 1
      timeout_seconds: 300
      location: EU
      priority: interactive
      retries: 1
  target: dev